### PR TITLE
feat: add requested changes

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**

### CODE REVIEW

**Comment by Adiomojeed** [comment]
Good evening, I am sorry for the late response. Weldone on the project
1. Wallet Page: The whitespace at the top of the card (My wallet balance) is too much. Add a margin button to the card
2. Performance page: Give the table row a border-left-width at the initial state before hover You will notice the table row contents are shifting when you hover
3. Profile page: The banner spans the entire width of the page and the height is more than what you used. The cards have border-radius. The border-bottom on account-settings is padded (not padded on design). Each input field should use col-12 on small screen. Input field height is 64px, you used 50px

**Comment by kaf-lamed-beyt** [comment]
Okay...

I'd work on these changes but it might be coming in late. I'm not feeling too good.

**Comment by Adiomojeed** [comment]
Okay, when will you be fit?

**Comment by kaf-lamed-beyt** [comment]
I'd try making it tomorrow...

If I'm not chanced, I'd let you know immediately

**Pull request merged**
