### PR TITLE
feat: add performance component

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
@Adiomojeed

**Comment by Adiomojeed** [comment]
Reviews - Follow the design strictly as it is in Figma. Perfection is important
Remove the z-index you set on  nav and aside. Why did you add it?
Don't style elements directly, assign a classname instead to avoid global override
Don't style using id, USE CLASSNAMES
Read on BEM methodology in class namings

Wallet Page:
Content spans more width than it is in the design
Font weight of price and font size is smaller
Card has a white background and span entire height of the page

Performance:
Doesn't span entire width
Adjust the paddings on the table
background-color on hover isn't same as on the design: check strictly, it is lighter and has a border-left
View attempts should be a link not text - No, I think it should be a modal, cyberPhym didn't design that. Ask him
Table is not responsive

Feedback Page:
Adjust the border color. It is not fully black and the width is much
You added a default value to the textarea, that's wrong. Use a placeholder instead
Button is aligned to right of the page and bigger

Profile:
Page banner spans the entire width of the dashboard
Contents are too close to the top
Kindly check the figma board for the profile and make necessary amendments
Input field height - 64 on figma, you are using 50
Button is bigger than it is in the deisgn

PLEASE, MAKE SURE THE REPLICATE THE DESIGN WITH AT LEAST 95% PERFECTION

**Comment by kaf-lamed-beyt** [comment]
> Button is bigger than it is in the design

That's the button size that was/is available, and I didn't want to break anything.

**Comment by kaf-lamed-beyt** [comment]
> You added a default value to the textarea, that's wrong. Use a placeholder instead

Adding a default value to the textarea isn't wrong. But no shit, would fix it.

**Comment by kaf-lamed-beyt** [comment]
> View attempts should be a link not text - No, I think it should be a modal, cyberPhym didn't design that. Ask him
Table is not responsive.

Yeah, I added that, as a dummy type. I'd make the amends.

> Remove the z-index you set on nav and aside. Why did you add it?

- If I remove it, the profile card would have a higher-order over the sidebar.
- the top background color on the profile page is behind the profile and account settings card (from the design), that's why I used the z-index.

**Comment by kaf-lamed-beyt** [comment]
> Don't style using id, USE CLASSNAMES

Why shouldn't I style with id?

> Read on BEM methodology in class namings

On it.

**Comment by kaf-lamed-beyt** [comment]
> Wallet Page:
Content spans more width than it is in the design

That's weird!

> Card has a white background and span entire height of the page

Ok, I'd work on that too.

**Comment by kaf-lamed-beyt** [comment]
>Performance:
Doesn't span entire width

Okay? Which component exactly?

> background-color on hover isn't same as on the design: check strictly, it is lighter and has a border-left.

!

Background color of the table row

**Comment by kaf-lamed-beyt** [comment]
> Doesn't span entire width

When you say, "doesn't span entire width" which component(s) exactly do you mean? 'cause from the design, :point_down: the cards at the top do not span the entire column.

Screenshot from 2021-01-15 03-19-37

Please elaborate. And also reply to the comments/questions I've asked previously so I don't end up going back and forth. 

@Adiomojeed

**Comment by Adiomojeed** [comment]
> > Button is bigger than it is in the design
> 
> That's the button size that was/is available, and I didn't want to break anything.
> 

You can actually add additional classnames when calling the component to make modifications

**Comment by Adiomojeed** [comment]
> > You added a default value to the textarea, that's wrong. Use a placeholder instead
> 
> Adding a default value to the textarea isn't wrong. But no shit, would fix it.

No, you shouldn't. Your value must be an empty string in its initial state. Any thing you want to display in the textarea should be in placeholder

**Comment by Adiomojeed** [comment]
> > View attempts should be a link not text - No, I think it should be a modal, cyberPhym didn't design that. Ask him
> Table is not responsive.
> 
> Yeah, I added that, as a dummy type. I'd make the amends.
> 
> > Remove the z-index you set on nav and aside. Why did you add it?
> 
> - If I remove it, the profile card would have a higher-order over the sidebar.
> - the top background color on the profile page is behind the profile and account settings card (from the design), that's why I used the z-index.

I already added z-index to them. You shouldn't even add a z-index of that value if it's not really important. Your z-index value is overlapping the modal

**Comment by Adiomojeed** [comment]
> > Don't style using id, USE CLASSNAMES
> 
> Why shouldn't I style with id?
> 
> > Read on BEM methodology in class namings
> 
> On it.

Best practice

**Comment by Adiomojeed** [comment]
> > Wallet Page:
> Content spans more width than it is in the design
> 
> That's weird!
> 
> > Card has a white background and span entire height of the page
> 
> Ok, I'd work on that too.

I am referring to the text width oh. It didn't use more than 60-70% of the card

**Comment by Adiomojeed** [comment]
> > Doesn't span entire width
> 
> When you say, "doesn't span entire width" which component(s) exactly do you mean? 'cause from the design, :point_down: the cards at the top do not span the entire column.
> 
> Screenshot from 2021-01-15 03-19-37
> 
> Please elaborate. And also reply to the comments/questions I've asked previously so I don't end up going back and forth. 
> 
> @Adiomojeed 

Can you please send a screenshot of the page you implemented so I can point it out. I can't access my system ATM

**Comment by kaf-lamed-beyt** [comment]
> > > Button is bigger than it is in the design
> > 
> > 
> > That's the button size that was/is available, and I didn't want to break anything.
> 
> You can actually add additional classnames when calling the component to make modifications

Yeah, I figured that out. I already started working on that.

**Comment by kaf-lamed-beyt** [comment]
> > > View attempts should be a link not text - No, I think it should be a modal, cyberPhym didn't design that. Ask him
> > > Table is not responsive.
> > 
> > 
> > Yeah, I added that, as a dummy type. I'd make the amends.
> > > Remove the z-index you set on nav and aside. Why did you add it?
> > 
> > 
> > 
> > * If I remove it, the profile card would have a higher-order over the sidebar.
> > * the top background color on the profile page is behind the profile and account settings card (from the design), that's why I used the z-index.
> 
> I already added z-index to them. You shouldn't even add a z-index of that value if it's not really important. Your z-index value is overlapping the modal

Okay.

**Comment by kaf-lamed-beyt** [comment]
> I am referring to the text width oh. It didn't use more than 60-70% of the card

Oh! now I get, Thanks.

**Comment by kaf-lamed-beyt** [comment]
> Can you please send a screenshot of the page you implemented so I can point it out. I can't access my system ATM

Screenshot from 2021-01-16 09-50-29

**Comment by Adiomojeed** [comment]
> > Can you please send a screenshot of the page you implemented so I can point it out. I can't access my system ATM
> 
> Screenshot from 2021-01-16 09-50-29
> 
I am referring to each col width, they are smaller. No enough padding. Reference the number section. The content is too close

**Comment by kaf-lamed-beyt** [comment]
Okay. I'd adjust them all.

**Pull request closed without merging**
